- name: Add nodejs plugin
  command: ~/.asdf/bin/asdf plugin-add nodejs
  register: nodejs_add
  failed_when: nodejs_add == 2

- name: Install nodejs
  command: ~/.asdf/bin/asdf install nodejs 14.18.0

- name: Set global nodejs version
  command: ~/.asdf/bin/asdf global nodejs 14.18.0

- name: Install "yarn" node.js package globally
  npm:
    name: yarn typescript eslint prettier nodemon ngrok
    global: yes
# - name: Install "typescript" node.js package globally
#   npm:
#     name: typescript
#     global: yes

# - name: Install "eslint" node.js package globally
#   npm:
#     name: eslint
#     global: yes

# - name: Install "prettier" node.js package globally
#   npm:
#     name: prettier
#     global: yes

# - name: Install "nodemon" node.js package globally
#   npm:
#     name: nodemon
#     global: yes

# - name: Install "ngrok" node.js package globally
#   npm:
#     name: ngrok
#     global: yes
