- name: Install ZSH
  become: yes
  package:
    state: present
    name: zsh

- name: Install oh-my-zsh
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended
    creates: ~/.oh-my-zsh

- name: Install git-extras
  become: yes
  package:
    state: present
    name: git-extras

- name: Install FZF
  become: yes
  package:
    state: present
    name: fzf

- name: Install syntax-highlight plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Install autosuggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Install starship theme
  become: yes
  shell:
    cmd: curl -sS https://starship.rs/install.sh | sh -s -- -y

- name: Symlink .zshrc
  file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/.zshrc"
    path: ~/.zshrc
    state: link
    force: yes

- name: Symlink starship.toml
  file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/starship.toml"
    path: ~/.config/starship.toml
    state: link
    force: yes
